spring:
  #配置redis缓存服务
  redis:
    host: 47.115.80.184
    port: 6379
  #  邮件配置
  mail:
    host: smtp.qq.com
    username: rhetthj@qq.com
    password: mdbutgfyixsubhad
    port: 465
    # 其它参数
    properties:
      mail:
        smtp:
          # 如果是用 SSL 方式，需要配置如下属性,使用qq邮箱的话需要开启
          ssl:
            enable: true
            required: true
          # 邮件接收时间的限制，单位毫秒
          timeout: 10000
          # 连接时间的限制，单位毫秒
          connectiontimeout: 10000
          # 邮件发送时间的限制，单位毫秒
          writetimeout: 10000
    default-encoding: utf-8